name: test-simple-js-action
on:
    workflow_dispatch:
      inputs:
        user_name:
          required: true
          type: string
          description: 'user name:'
        benchmark_file:
          required: true
          type: string
          description: 'BenchMark file name:'
        source_file:
          required: true
          type: string
          description: 'Source File Name:'
        swagger_version:
          required: true
          type: string
          description: 'openapi version:'
jobs:
  simple_job:
    runs-on: ubuntu-latest
    name: validator
    steps:
      - name: run validations
        id: step1
        uses: kushal-omnius/openapi-validations@v1.1.2
        with:
          who-to-greet:  ${{ github.event.inputs.user_name }}
          benchmark_file:  ${{ github.event.inputs.benchmark_file }}
          source_file:  ${{ github.event.inputs.source_file }}
          openapi_version:  ${{ github.event.inputs.swagger_version }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: |
          echo "The time was ${{ steps.step1.outputs.time }}"
          echo "The time was ${{ steps.step1.outputs.swagger_validation_results }}"
          echo "The time was ${{ steps.step1.outputs.openapi_diff_results }}"
        
